### ISSUE TITLE
Profile installation issues

### ISSUE THREAD

**Issue by weiyong** [micromdm/micromdm#907] opened 2023-07-27 09:59 UTC
### What version of `micromdm` are you using?
micromdm version v1.8.0
### What `micromdm` command did you run?
/v1/commands   request_type=InstallProfile
### What did you expect to see?
The signing profile certificate generated on July 12th was able to install the provisioning profile, distribute single applications, and receive the quit command until July 17th. After the command was sent to the MicroMDM server, the server logged a message saying “queued event for device”, but the webhook callbacks were not triggered. Any requests with webhook URLs did not receive callbacks. However, manual installation and removal of the MDM certificate did trigger callbacks for mdm.Authenticate and mdm.TokenUpdate. Occasionally, the error message “no blueprints to apply” was encountered.

This is already in our enroll payload:

{"request_type":"InstallProfile","payload":"MIA...","udid":"00008103-001D3939..."}

### What did you see instead?
 All webhook  are asynchronous without callback

**Comment by korylprince** [comment] 2023-07-27 23:45
MDM commands _are_ asynchronous. [This comment](https://github.com/micromdm/micromdm/issues/903#issuecomment-1642251564) has a basic description of how a device receives a command and responds.

It sounds like you're queueing commands successfully, but the device is not checking in to get the command(s) in a timely manner. 

This could be because:

- MicroMDM is having trouble contacting Apple's APNS servers (which should be logged)
- The device is not receiving APNS notifications from Apple
- The device can't reach the MDM server

Also, it would be useful to upgrade to MicroMDM 1.11, which should be completely backwards compatible and includes bug fixes related to logging some errors.

**Comment by weiyong** [comment] 2023-07-28 02:58
> MDM commands _are_ asynchronous. [This comment](https://github.com/micromdm/micromdm/issues/903#issuecomment-1642251564) has a basic description of how a device receives a command and responds.
> 
> It sounds like you're queueing commands successfully, but the device is not checking in to get the command(s) in a timely manner.
> 
> This could be because:
> 
> * MicroMDM is having trouble contacting Apple's APNS servers (which should be logged)
> * The device is not receiving APNS notifications from Apple
> * The device can't reach the MDM server
> 
> Also, it would be useful to upgrade to MicroMDM 1.11, which should be completely backwards compatible and includes bug fixes related to logging some errors.
 
Thank you very much for your reply, I still have a few questions that need your guidance:
1. What is the APNS server? From the mobile device management of the description file, it can be seen that "use and develop APNS is No", and the issue of the certificate issued before is also No. Does it affect this?
2. Will the MicroMDM server be restricted and affect the webhook callback, such as a firewall; if so, what methods can I use to check or which domain names (addresses) may be restricted;
3. If you upgrade to MicroMDM 1.11, which startup parameters can troubleshoot this problem?
  Looking forward to your reply.

**Comment by korylprince** [comment] 2023-07-28 23:45
1. APNS is the Apple Push Notification Service. APNS is an integral part of MDM. The [quickstart guide](https://github.com/micromdm/micromdm/blob/main/docs/user-guide/quickstart.md#configure-an-apns-certificate) covers adding the APNS certificate to MicroMDM. I'm not sure what document you're referencing.
    - Note: APNS is also the service apps use to send notifications, so most documentation you'll see on it is about that use case.
2. I'm not really sure what you're asking here. The webhook is a URL that you specify via the `-command-webhook-url`. MicroMDM POSTs events to the URL as described [here](https://github.com/micromdm/micromdm/blob/main/docs/user-guide/api-and-webhooks.md). It's up to you to make sure the server running MicroMDM can access the URL you specify.
3. The `-http-debug` flag can be useful to see the actual requests/responses MicroMDM is receiving/sending. To be clear though, this is for incoming requests. Requests sent to the webhook by MicroMDM don't have extra logging when this flag is enabled. But v1.11 also fixes a bug that caused some errors to not be logged properly.

**Comment by weiyong** [comment] 2023-07-29 02:40
> 1. APNS is the Apple Push Notification Service. APNS is an integral part of MDM. The [quickstart guide](https://github.com/micromdm/micromdm/blob/main/docs/user-guide/quickstart.md#configure-an-apns-certificate) covers adding the APNS certificate to MicroMDM. I'm not sure what document you're referencing.
>    
>    * Note: APNS is also the service apps use to send notifications, so most documentation you'll see on it is about that use case.
> 2. I'm not really sure what you're asking here. The webhook is a URL that you specify via the `-command-webhook-url`. MicroMDM POSTs events to the URL as described [here](https://github.com/micromdm/micromdm/blob/main/docs/user-guide/api-and-webhooks.md). It's up to you to make sure the server running MicroMDM can access the URL you specify.
> 3. The `-http-debug` flag can be useful to see the actual requests/responses MicroMDM is receiving/sending. To be clear though, this is for incoming requests. Requests sent to the webhook by MicroMDM don't have extra logging when this flag is enabled. But v1.11 also fixes a bug that caused some errors to not be logged properly.

The enroll.mobileconfig file can be manually installed normally or information can be obtained through`/v1/devices` devices, but cannot be installed through install_ profile pushes the file. Manually install and remove enrol.mobileconfig through install_ profile push file or InstalledApplicationList to obtain a list of device installation apps. After seeing "queued event for device" in the MicroMDM log, there is no error reported and the device has not responded. MicroMDM startup specifies parameters such as -http-debug, -api-key, -tls=false, -command-webhook-url, etc. I would like to ask why this is the case

**Comment by korylprince** [comment] 2023-07-31 03:01
If the device is enrolled, and it's not checking in after queuing a command (and therefore sending the device an APNS notification), then it's almost certainly one of the issues I mentioned [above](https://github.com/micromdm/micromdm/issues/907#issuecomment-1654767016).

Also, since I forgot to mention it before, the "no blueprints to apply" message can safely be ignored. It just means that you haven't set up a [Blueprint](https://github.com/micromdm/micromdm/wiki/Provisioning-Users-with-Blueprints), which is an optional feature of MicroMDM.

**Comment by weiyong** [comment] 2023-07-31 04:35
> If the device is enrolled, and it's not checking in after queuing a command (and therefore sending the device an APNS notification), then it's almost certainly one of the issues I mentioned [above](https://github.com/micromdm/micromdm/issues/907#issuecomment-1654767016).
> 
> Also, since I forgot to mention it before, the "no blueprints to apply" message can safely be ignored. It just means that you haven't set up a [Blueprint](https://github.com/micromdm/micromdm/wiki/Provisioning-Users-with-Blueprints), which is an optional feature of MicroMDM.

micromdm upgraded to 1.11, see micromdm still no error message：
[app@vm-centos mdmmicro]$ micromdm -version 
micromdm version v1.11.0
[app@vm-centos mdmmicro]$ cat mdmmicro.log  | grep 'checkin' 
                                <string>https://push.url/mdm/checkin</string>
                                <string>https://push.url/mdm/checkin</string>
PUT /mdm/checkin HTTP/1.1
Content-Type: application/x-apple-aspen-mdm-checkin
transport=http method=PUT status=200 proto=HTTP/1.1 host=100.127.251.139 user_agent=MDM/1.0 path=/mdm/checkin
                                <string>https://push.url/mdm/checkin</string>
PUT /mdm/checkin HTTP/1.1
Content-Type: application/x-apple-aspen-mdm-checkin
transport=http method=PUT status=200 proto=HTTP/1.1 host=100.127.251.205 user_agent=MDM/1.0 path=/mdm/checkin
PUT /mdm/checkin HTTP/1.1
Content-Type: application/x-apple-aspen-mdm-checkin
transport=http method=PUT status=200 proto=HTTP/1.1 host=100.127.251.215 user_agent=MDM/1.0 path=/mdm/checkin
PUT /mdm/checkin HTTP/1.1
Content-Type: application/x-apple-aspen-mdm-checkin
transport=http method=PUT status=200 proto=HTTP/1.1 host=100.127.251.244 user_agent=MDM/1.0 path=/mdm/checkin
[app@vm-centos mdmmicro]$ cat mdmmicro.log  | grep 'component=scep' 
component=scep op=GetCACert error=null took=12.503µs
component=scep method=GET status=200 proto=HTTP/1.1 host=100.127.251.180 user_agent="profiled/1.0 CFNetwork/1335.0.3 Darwin/21.6.0" path="/scep?operation=GetCACert&message=Device%20Management%20Identity%20Certificate"
component=scep op=GetCACaps error=null took=18.429µs
component=scep method=GET status=200 proto=HTTP/1.1 host=100.127.251.215 user_agent="profiled/1.0 CFNetwork/1335.0.3 Darwin/21.6.0" path="/scep?operation=GetCACaps&message=Device%20Management%20Identity%20Certificate"
component=scep op=PKIOperation error=null took=9.647446ms
component=scep method=POST status=200 proto=HTTP/1.1 host=100.127.251.217 user_agent="profiled/1.0 CFNetwork/1335.0.3 Darwin/21.6.0" path="/scep?operation=PKIOperation"

**Comment by weiyong** [comment] 2023-07-31 05:34
> If the device is enrolled, and it's not checking in after queuing a command (and therefore sending the device an APNS notification), then it's almost certainly one of the issues I mentioned [above](https://github.com/micromdm/micromdm/issues/907#issuecomment-1654767016).
> 
> Also, since I forgot to mention it before, the "no blueprints to apply" message can safely be ignored. It just means that you haven't set up a [Blueprint](https://github.com/micromdm/micromdm/wiki/Provisioning-Users-with-Blueprints), which is an optional feature of MicroMDM.

[app@vm-centos mdmmicro]$ cat mdmmicro.log  | grep 'api.push.apple.com'
[app@vm-centos mdmmicro]$  curl https://api.push.apple.com 
@@+���Unexpected HTTP/1.x request: GET / 

I did not find the `api.push.apple.com` request in the micromdm log, curl `api.push.apple.com` found that it was rejected, but the browser access is normal, does it have something to do with this

**Comment by korylprince** [comment] 2023-08-01 02:20
It sounds like you're not having an issue with MicroMDM sending push notifications to Apple, then.

If devices aren't checking in after queuing a command, then the issue is likely:

- The device is not receiving APNS notifications from Apple
- The device can't reach your MicroMDM server

Neither of those issues would log any error messages in MicroMDM logs, as the issue doesn't really have anything to do with MicroMDM.

**Comment by korylprince** [comment] 2023-08-31 18:22
There hasn't been any activity on this, so I'm going to go ahead and close this issue. If you have any further issues/questions, feel free to reopen.

**Closed by korylprince** 2023-08-31 18:22 UTC
