### ISSUE TITLE
 Mobileconfig fails to be installed on the iPhone sometime

### ISSUE THREAD

**Issue by zxyzhouxiaoyun** [micromdm/micromdm#893] opened 2023-06-18 08:45 UTC

**Comment by jessepeterson** [comment] 2023-06-18 22:05
Can you give server logs? Error messages? Device logs? Anything we can use to help?

**Comment by zxyzhouxiaoyun** [comment] 2023-06-19 00:43
> Can you give server logs? Error messages? Device logs? Anything we can use to help?

profile installation fails almost 10% of the time，I checked the reason is probably the network, but the probability of other people's installation failure is very small, I do not know where the configuration problem。This has been bothering me for two months

**Comment by korylprince** [comment] 2023-07-31 03:12
@zxyzhouxiaoyun, as you mentioned in #908, your device is not checking in when this occurs. I would highly suggest reading my comments in #903 and #907, as both of those issues are related to this issue.

Like I mentioned in those issues, your problem is likely because:

- MicroMDM is having trouble contacting Apple's APNS servers (which should be logged)
- The device is not receiving APNS notifications from Apple
- The device can't reach your MicroMDM server

All of those problems are something you'll have to fix in your environment (firewall, network connectivity, etc). Upgrading to v1.11 (which has some bug fixes related to logging errors) and using the `-http-debug` may be able to help you diagnose the issue, but if the device just isn't checking in, there's not much MicroMDM can do about that.

**Comment by zxyzhouxiaoyun** [comment] 2023-07-31 03:12
> Can you give server logs? Error messages? Device logs? Anything we can use to help?

server logs 
Jul 30 23:24:00 iZuf6b2y92juwkwsdw9bnmZ micromdm[20693]: component=scep method=GET status=200 proto=HTTP/2.0 host=117.148.81.122 user_agent="profiled/1.0 CFNetwork/1399 Darwin/22.1.0" path="/scep?operation=GetCACert&message=Device%20Management%20Identity%20Certificate"
Jul 30 23:24:00 iZuf6b2y92juwkwsdw9bnmZ micromdm[20693]: transport=http method=GET status=200 proto=HTTP/2.0 host=117.148.81.122 user_agent="profiled/1.0 CFNetwork/1399 Darwin/22.1.0" path="/scep?operation=GetCACert&message=Device%20Management%20Identity%20Certificate"
Jul 30 23:24:00 iZuf6b2y92juwkwsdw9bnmZ micromdm[20693]: component=scep method=GET status=200 proto=HTTP/2.0 host=117.148.81.122 user_agent="profiled/1.0 CFNetwork/1399 Darwin/22.1.0" path="/scep?operation=GetCACaps&message=Device%20Management%20Identity%20Certificate"
Jul 30 23:24:00 iZuf6b2y92juwkwsdw9bnmZ micromdm[20693]: transport=http method=GET status=200 proto=HTTP/2.0 host=117.148.81.122 user_agent="profiled/1.0 CFNetwork/1399 Darwin/22.1.0" path="/scep?operation=GetCACaps&message=Device%20Management%20Identity%20Certificate"
Jul 30 23:24:00 iZuf6b2y92juwkwsdw9bnmZ micromdm[20693]: component=scep method=POST status=200 proto=HTTP/2.0 host=117.148.81.122 user_agent="profiled/1.0 CFNetwork/1399 Darwin/22.1.0" path="/scep?operation=PKIOperation"
Jul 30 23:24:00 iZuf6b2y92juwkwsdw9bnmZ micromdm[20693]: transport=http method=POST status=200 proto=HTTP/2.0 host=117.148.81.122 user_agent="profiled/1.0 CFNetwork/1399 Darwin/22.1.0" path="/scep?operation=PKIOperation"
Jul 30 23:24:00 iZuf6b2y92juwkwsdw9bnmZ micromdm[20693]: transport=http method=PUT status=500 proto=HTTP/2.0 host=117.148.81.122 user_agent=MDM/1.0 path=/mdm/checkin

device log ： profile install faild

**Comment by zxyzhouxiaoyun** [comment] 2023-07-31 03:15
> @zxyzhouxiaoyun, as you mentioned in #908, your device is not checking in when this occurs. I would highly suggest reading my comments in #903 and #907, as both of those issues are related to this issue.
> 
> Like I mentioned in those issues, your problem is likely because:
> 
> * MicroMDM is having trouble contacting Apple's APNS servers (which should be logged)
> * The device is not receiving APNS notifications from Apple
> * The device can't reach your MicroMDM server
> 
> All of those problems are something you'll have to fix in your environment (firewall, network connectivity, etc). Upgrading to v1.11 (which has some bug fixes related to logging errors) and using the `-http-debug` may be able to help you diagnose the issue, but if the device just isn't checking in, there's not much MicroMDM can do about that.



> @zxyzhouxiaoyun, as you mentioned in #908, your device is not checking in when this occurs. I would highly suggest reading my comments in #903 and #907, as both of those issues are related to this issue.
> 
> Like I mentioned in those issues, your problem is likely because:
> 
> * MicroMDM is having trouble contacting Apple's APNS servers (which should be logged)
> * The device is not receiving APNS notifications from Apple
> * The device can't reach your MicroMDM server
> 
> All of those problems are something you'll have to fix in your environment (firewall, network connectivity, etc). Upgrading to v1.11 (which has some bug fixes related to logging errors) and using the `-http-debug` may be able to help you diagnose the issue, but if the device just isn't checking in, there's not much MicroMDM can do about that.
So I'm going to upgrade to 1.11 and use http-debug to find out why

**Comment by zxyzhouxiaoyun** [comment] 2023-07-31 03:16
> @zxyzhouxiaoyun, as you mentioned in #908, your device is not checking in when this occurs. I would highly suggest reading my comments in #903 and #907, as both of those issues are related to this issue.
> 
> Like I mentioned in those issues, your problem is likely because:
> 
> * MicroMDM is having trouble contacting Apple's APNS servers (which should be logged)
> * The device is not receiving APNS notifications from Apple
> * The device can't reach your MicroMDM server
> 
> All of those problems are something you'll have to fix in your environment (firewall, network connectivity, etc). Upgrading to v1.11 (which has some bug fixes related to logging errors) and using the `-http-debug` may be able to help you diagnose the issue, but if the device just isn't checking in, there's not much MicroMDM can do about that.

So I'm going to upgrade to 1.11 and use http-debug to find out why

**Comment by korylprince** [comment] 2023-07-31 03:28
The last line, particularly the `status=500` part, is definitely an issue. Upgrading to v1.11 and using `-http-debug` to view the request and response in the logs for that endpoint should hopefully shed some light on the issue.

I'll reopen this for now. Please post the HTTP debug logs.

**Comment by zxyzhouxiaoyun** [comment] 2023-07-31 03:38
> The last line, particularly the `status=500` part, is definitely an issue. Upgrading to v1.11 and using `-http-debug` to view the request and response in the logs for that endpoint should hopefully shed some light on the issue.
> 
> I'll reopen this for now. Please post the HTTP debug logs.
Okay, I'll upgrade to the next version. I used to use 1.9, but I don't seem to have a status=500 log anymore

**Comment by zxyzhouxiaoyun** [comment] 2023-07-31 03:39
> Okay, I'll upgrade to the next version. I used to use 1.9, but I don't seem to have a status=500 log anymore

Okay, I'll upgrade to the next version. I used to use 1.9, but I don't seem to have a status=500 log anymore

**Comment by zxyzhouxiaoyun** [comment] 2023-07-31 03:39
> The last line, particularly the `status=500` part, is definitely an issue. Upgrading to v1.11 and using `-http-debug` to view the request and response in the logs for that endpoint should hopefully shed some light on the issue.
> 
> I'll reopen this for now. Please post the HTTP debug logs.

Okay, I'll upgrade to the next version. I used to use 1.9, but I don't seem to have a status=500 log anymore

**Comment by zxyzhouxiaoyun** [comment] 2023-08-01 07:42
> Contributor

transport=http method=PUT status=200 proto=HTTP/2.0 host=60.182.136.151 user_agent=MDM/1.0 path=/mdm/checkin
level=info msg="update device from event" err="retrieve device with udid 00008120-001E30AA2E03C01E: not found: Device key 00008120-001E30AA2E03C01E"

The device with the debug parameter turned on looks successful, but does not have checkin's webhook

**Comment by zxyzhouxiaoyun** [comment] 2023-08-01 07:43
> The last line, particularly the `status=500` part, is definitely an issue. Upgrading to v1.11 and using `-http-debug` to view the request and response in the logs for that endpoint should hopefully shed some light on the issue.
> 
> I'll reopen this for now. Please post the HTTP debug logs.

transport=http method=PUT status=200 proto=HTTP/2.0 host=60.182.136.151 user_agent=MDM/1.0 path=/mdm/checkin
level=info msg="update device from event" err="retrieve device with udid 00008120-001E30AA2E03C01E: not found: Device key 00008120-001E30AA2E03C01E"

The device with the debug parameter turned on looks successful, but does not have checkin's webhook

**Comment by zxyzhouxiaoyun** [comment] 2023-08-02 00:46
> The last line, particularly the `status=500` part, is definitely an issue. Upgrading to v1.11 and using `-http-debug` to view the request and response in the logs for that endpoint should hopefully shed some light on the issue.
> 
> I'll reopen this for now. Please post the HTTP debug logs.

---END Request---
err="error retrieving device certificate: CMS verify MDM Signed Message: pkcs7: signing time \"2023-08-02T00:44:48Z\" is outside of certificate validity \"2023-08-02T00:44:50Z\" to \"2024-08-01T00:44:50Z\""
---BEGIN Response---
HTTP/1.1 500 Internal Server Error
Connection: close

**Comment by korylprince** [comment] 2023-08-02 01:49
That error indicates you're hitting [this issue](https://github.com/micromdm/micromdm/issues/886), which happens when your devices are out of time sync with your server. You can use the `-device-signature-skew` flag to also allow a configurable time skew if you can't get your devices' time synced. A reasonable value is 5 minutes: `-device-signature-skew 5m`

**Comment by zxyzhouxiaoyun** [comment] 2023-08-02 03:19
> That error indicates you're hitting [this issue](https://github.com/micromdm/micromdm/issues/886), which happens when your devices are out of time sync with your server. You can use the `-device-signature-skew` flag to also allow a configurable time skew if you can't get your devices' time synced. A reasonable value is 5 minutes: `-device-signature-skew 5m`

Thanks for seeing. It's time to pack a new bag

**Comment by korylprince** [comment] 2023-08-07 01:33
I'm going to go ahead and close this issue, as it seems like the root cause has been identified. If this doesn't solve the issue, feel free to reopen.

**Closed by korylprince** 2023-08-07 01:33 UTC
Labels: needs-info
