### ISSUE TITLE
Invalid Certificate Signature

### ISSUE THREAD

**Issue by HernanPaez** [micromdm/micromdm#723] opened 2021-02-08 14:38 UTC
### What version of `micromdm` are you using?
1.7.1
### What `micromdm` command did you run?
```
mdmctl mdmcert vendor -password=MyAwesomePassword -country=US -email=my@email.com  
mdmctl mdmcert push -password=MyAwesomePassword -country=US -email=my@email.com  
mdmctl mdmcert vendor -sign -cert=./mdm-certificates/mdm.cer -password=MyAwesomePassword
````
### What did you expect to see?
Success creating the Apple Push Certificate
### What did you see instead?
I followed the quickstart guide but I am having a problem when I upload the PushCertificateRequest.plist file
The Apple Push Certificates Portal returns me this error:
```
Certificate Signature Verification failed
Certificate Signature Verification failed because the signature is invalid.
```
I am trying to renew an existing certificate, but the portal returns me the same error if I want to create a new one also

**Comment by HernanPaez** [comment] 2021-02-08 16:23
I don't know if the Apple WWDR Certificate expiration is the main issue behind this problem. Here is more info:

[Apple Worldwide Developer Relations Intermediate Certificate Expiration](https://developer.apple.com/support/expiration/). 

I tried to replace the wwdrIntermediaryURL and appleRootCAURL urls with the ones you can found in the [Apple PKI Site](https://www.apple.com/certificateauthority/) but I hadn't any luck with the new certificates I created.

**Comment by choehn-signogy** [comment] 2021-02-08 16:38
Having the same issue today. Puzzled

**Comment by rodchristiansen** [comment] 2021-02-08 22:28
I am having the same issue. Could just be an issue on Apple’s side or they changed the plist format? The plist created by micro isn’t being taken by identity.apple.com

**Comment by rodchristiansen** [comment] 2021-02-08 22:29
It’s probably related to the certificate expired on January 28th. I had to add and trust the old intermediate certificate to my Ubuntu instance as I could renew the push cert.

**Comment by Lepidopteron** [comment] 2021-02-09 08:36
@rodchristiansen What do you mean with:

> add and trust the old intermediate certificate

The 'new' intermediate certificate should be valid from 19th Feb 2020?

Did renewing the cert did only work for you, when you used the cert expiring on 02/07/2023 21:48:47 UTC ?
Which can be found here: https://www.apple.com/certificateauthority/

**Comment by HernanPaez** [comment] 2021-02-09 13:39
I tried with both certificates and I wasn't able to renew or either create a new push certificate.

- First I tried with the 'normal' certificate (expiring in 2023) and the Apple Root CA.
- After that I tried with the G3 certificate (expiring in 2030) and the Apple Root CA - G3 and it didn't work.
- Evaluating the G3 certificate I discovered that the certificate chain includes the Apple Root CA (and not the G3, my bad) I modified the mdmctl tool to use this certificates but it didn't work

Comparing the certificates side-by-side I noticed that the public key signature algorithm is different. I don't know if this has anything to do with this error but the new one is using SHA-256 with RSA Encryption and the old one is using SHA-1 with RSA Encryption

**Comment by zainspresso** [comment] 2021-02-09 13:56
Same issue here...

**Comment by groob** [comment] 2021-02-09 15:13
I don't have access to the MDM.CSR myself, but looking at the documentation on the apple website, I can't tell that anything has changed with their process. 

https://developer.apple.com/documentation/devicemanagement/implementing_device_management/setting_up_push_notifications_for_your_mdm_customers

https://github.com/micromdm/micromdm/blob/4ad71810c7f9a3405ef950384541e22f80fe0e29/pkg/crypto/mdmcertutil/certutil.go#L82

If you're modifying the source, don't hesitate to share the diff. Maybe I can help there.

**Comment by zainspresso** [comment] 2021-02-09 15:20
@groob If you want I can share my development MDM CER. I tried modifying the CA links but nothing works...

**Comment by choehn-signogy** [comment] 2021-02-09 15:23
I compared the old 2018 Protocol Reference (pdf) to the actual documentation other website and would also say there is nothing new.

@groob Basically it is a URL change in certutil.go
`	//wwdrIntermediaryURL = "https://developer.apple.com/certificationauthority/AppleWWDRCA.cer"
	wwdrIntermediaryURL = "https://www.apple.com/certificateauthority/AppleWWDRCAG3.cer"`

**Comment by groob** [comment] 2021-02-09 15:26
Note that if you're on linux, there's a recent bug where G3 was removed from the cert store. Is anyone getting these failures running `mdmctl` on a mac?

**Comment by Lepidopteron** [comment] 2021-02-09 15:34
Here are my insights. As I was coping with this issue since yesterday, I wanted to share my insights:
Apple's documentation did not change:
https://developer.apple.com/documentation/devicemanagement/implementing_device_management/setting_up_push_notifications_for_your_mdm_customers

The new certificate that is used for `MDM CSR` since 2021/01/28 as mentioned here: https://developer.apple.com/support/expiration/

Seems to be really used, although the documentation was *not* updated in the above page.
When checking the mdm.cer file, downloaded in your https://developer.apple.com certificates section, you will see that the Certificate Authority is `http://certs.apple.com/wwdrg3.der` - which is the new certificate mentioned here: https://developer.apple.com/support/expiration/

for clarification, this does not produce an output:
```
curl http://certs.apple.com/wwdrg3.der -o wwdrg3.der
curl https://www.apple.com/certificateauthority/AppleWWDRCAG3.cer -o AppleWWDRCAG3.cer
diff wwdrg3.der AppleWWDRCAG3.cer
```

Fine, so we updated the endpoint mentioned here:
https://github.com/micromdm/micromdm/blob/5e10dd1caf76546a47014dc6253c2fb723b7da1e/pkg/crypto/mdmcertutil/certutil.go#L75
to be `http://certs.apple.com/wwdrg3.der` saved and rebuilt via `make build` and ran the serve command again.

Same procedure to generate the `mdm.cer` file, uploaded the .plist and again had the statement

```
Certificate Signature Verification failed
Certificate Signature Verification failed because this [signature](https://www.apple.com/business/apps/#management) invalid.
```

--------

Just because I was quite in doubt, whether the entire approach might be somehow not working on `micromdm` I did rewrite the Push Request logic as a bash script myself (running on Mac).
If you want to test this on Linux:

- Replace `curl` with `wget`
- Replace `base64` with `base64 -w0`

```
## Fetch AppleIncRootCertificate.cer
curl https://www.apple.com/appleca/AppleIncRootCertificate.cer -o $(echo `pwd`)/mdm-certificates/AppleIncRootCertificate.cer
openssl x509 -inform der -in $(echo `pwd`)/mdm-certificates/AppleIncRootCertificate.cer -out $(echo `pwd`)/mdm-certificates/AppleIncRootCertificate.pem
openssl x509 -fingerprint -sha256 -noout -in $(echo `pwd`)/mdm-certificates/AppleIncRootCertificate.pem

openssl x509 -inform der \
    -in $(echo `pwd`)/mdm-certificates/AppleIncRootCertificate.cer \
    -out $(echo `pwd`)/mdm-certificates/AppleIncRootCertificate.pem

## Fetch AppleWWDRCAG3.cer
curl http://certs.apple.com/wwdrg3.der -o $(echo `pwd`)/mdm-certificates/wwdrg3.der -o $(echo `pwd`)/mdm-certificates/AppleWWDRCA.cer
# Alternative Path to new cert
#curl https://www.apple.com/certificateauthority/AppleWWDRCAG3.cer -o $(echo `pwd`)/mdm-certificates/AppleWWDRCA.cer
# Old Cert Path
#curl https://developer.apple.com/certificationauthority/AppleWWDRCA.cer -o $(echo `pwd`)/mdm-certificates/AppleWWDRCA.cer

openssl x509 -inform der \
    -in $(echo `pwd`)/mdm-certificates/AppleWWDRCA.cer \
    -out $(echo `pwd`)/mdm-certificates/AppleWWDRCA.pem
openssl verify -verbose \
    -CAfile $(echo `pwd`)/mdm-certificates/AppleIncRootCertificate.pem \
    $(echo `pwd`)/mdm-certificates/AppleWWDRCA.pem

# mdm.cer --> mdm.pem
openssl x509 -inform DER -outform PEM \
    -in $(echo `pwd`)/mdm-certificates/mdm.cer \
    -out $(echo `pwd`)/mdm-certificates/mdm.pem

# verify
openssl verify -verbose \
    -CAfile $(echo `pwd`)/mdm-certificates/AppleIncRootCertificate.pem \
    -untrusted $(echo `pwd`)/mdm-certificates/AppleWWDRCA.pem \
    $(echo `pwd`)/mdm-certificates/mdm.pem


openssl verify -verbose \
    -CAfile $(echo `pwd`)/mdm-certificates/AppleIncRootCertificate.pem \
    -untrusted $(echo `pwd`)/mdm-certificates/wwdrg3.pem \
    $(echo `pwd`)/mdm-certificates/mdm.pem


openssl req -inform PEM -outform DER \
    -in $(echo `pwd`)/mdm-certificates/PushCertificateRequest.csr \
    -out $(echo `pwd`)/mdm-certificates/PushCertificateRequest.csr.der

####################
# Be aware that you have to enter the password here, which was used for the push cert csr
####################
openssl sha1 -sign $(echo `pwd`)/mdm-certificates/PushCertificatePrivateKey.key \
    -out $(echo `pwd`)/mdm-certificates/PushCertificateRequest.csr.der.sig \
    $(echo `pwd`)/mdm-certificates/PushCertificateRequest.csr.der


####################
# Preparing the .plist file, which we want to upload at https://identity.apple.com/pushcert/
####################
base64 $(echo `pwd`)/mdm-certificates/PushCertificateRequest.csr.der >$(echo `pwd`)/mdm-certificates/PushCertificateRequest.csr.der.b64
base64 $(echo `pwd`)/mdm-certificates/PushCertificateRequest.csr.der.sig >$(echo `pwd`)/mdm-certificates/PushCertificateRequest.csr.der.sig.b64

cat <<EOF >$(echo `pwd`)/mdm-certificates/ScriptedPushCert.plist
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
    <dict>
        <key>PushCertCertificateChain</key>
        <string>
            $(<$(echo `pwd`)/mdm-certificates/mdm.pem)
            $(<$(echo `pwd`)/mdm-certificates/AppleWWDRCA.pem)
            $(<$(echo `pwd`)/mdm-certificates/AppleIncRootCertificate.pem)
        </string>
        <key>PushCertRequestCSR</key>
        <string>
            $(<$(echo `pwd`)/mdm-certificates/PushCertificateRequest.csr.der.b64)
        </string>
        <key>PushCertSignature</key>
        <string>
            $(<$(echo `pwd`)/mdm-certificates/PushCertificateRequest.csr.der.sig.b64)
        </string>
    </dict>
    </plist>
EOF

base64 $(echo `pwd`)/mdm-certificates/ScriptedPushCertPlain.plist >$(echo `pwd`)/mdm-certificates/ScriptedPushCert.plist
```

I did file a Request to Apple with the above mentioned insights, as I am currently out of any new ideas. Maybe it does help someone of you....

**Comment by groob** [comment] 2021-02-09 15:57
Thanks Tobias, that's really helpful. 

I am biased towards thinking Apple broke something on their own end, unintentionally and it will get fixed once they notice. 

In the past I've had some luck getting more details out of the identity.apple.com website by looking at the HTTP response. Before you upload the plist to Apple, open your Chrome or Firefox developer tools and make sure logging is enabled. Then upload the plist and find the XHR request. The response might contain a more descriptive error of why the plist is being rejected.

**Comment by rodchristiansen** [comment] 2021-02-09 16:49
The XHR request shows 
```
{"ErrorCode":-80018,"ErrorMessage":"Certificate Signature Verification failed","ErrorDescription":"Certificate Signature Verification failed because the http://www.apple.com/business/mdm\" target=\"_blank\">signature</a> is invalid."}
```

Google search turned up this [StackOverflow](https://stackoverflow.com/questions/9808203/apple-mdm-csr-signing-fails-on-signature-validation) which mentions the issue was with the certificate chain.

**Comment by groob** [comment] 2021-02-09 17:09
Could someone try the following? Go through the quickstart process from scratch, and do not reuse any of the existing private keys to create the request plist?

**Comment by rodchristiansen** [comment] 2021-02-09 17:12
That plist I used was from quick start process from scratch. I'll let others test and see if they report the same.

**Comment by groob** [comment] 2021-02-09 17:13
you started with a brand new "MDM CSR" from the dev portal, using a new private key to get it?

**Comment by rodchristiansen** [comment] 2021-02-09 17:22
Yes brand new MDM CSR on Saturday. My API calls were broken and I ran through every step as if it I was a new MDM. But couldn’t pass the identity upload to renew the push cert -- creating a new push cert fails the same way.

[My issue](https://macadmins.slack.com/archives/C19RTE0L9/p1612562656088400) turned out to be the cert being untrusted on my Ubuntu instance, preventing APIs  -- api.push.apple.com uses an [old Certificate](https://www.geotrust.com/resources/root_certificates/certificates/GeoTrust_Global_CA.pem) from Geotrust which is not trusted anymore on Ubuntu/Linux

**Comment by Lepidopteron** [comment] 2021-02-09 17:30
> That plist I used was from quick start process from scratch. I'll let others test and see if they report the same.

Same here. Did generate one from scratch but did also try an upgrade. Both approaches failed.

**Comment by Lepidopteron** [comment] 2021-02-09 17:34
> ```
> {"ErrorCode":-80018,"ErrorMessage":"Certificate Signature Verification failed","ErrorDescription":"Certificate Signature Verification failed because the http://www.apple.com/business/mdm\" target=\"_blank\">signature</a> is invalid."}
> ```

I can confirm this. I got the same error code.

**Comment by zainspresso** [comment] 2021-02-09 17:40
Thanks @rodchristiansen this worked for me! But yes, for me requesting a new certificate via identity.apple.com still doesn't work

**Comment by korylprince** [comment] 2021-02-09 19:03
I tried these steps on both Arch Linux and on macOS 10.15.7 (19H114), and I'm still getting the "Certificate Signature Verification failed because the signing certificate  is expired." message:

* `mdmctl mdmcert.download -new -email=<my email>`
* `mdmctl mdmcert.download -decrypt=<file from email>`
* Upload mdmcert.download.push.req to try and renew push cert

So has anyone actually managed to get a push cert to renew?

**Comment by korylprince** [comment] 2021-02-09 19:30
I don't think this is necessarily everyone's issue, the request that is generated is using mdmcert.download's cert which expired on December 16th :disappointed: 

Once I do a bit more research I'm going to try and reach out to them.

**Comment by jessepeterson** [comment] 2021-02-09 19:53
+1 on getting cert request signed at identity.apple.com here as well. Completely new MDM CSR vendor cert from scratch on the dev portal, and new attempt at a push cert (via mdmcert.download cert process fwiw).

**Comment by korylprince** [comment] 2021-02-09 19:58
@jessepeterson just to be clear, you're saying you were able to successfully renew a push cert with Apple? Can you check the signing cert expiration in your request you uploaded to Apple?

**Comment by jessepeterson** [comment] 2021-02-09 20:00
@korylprince Sorry, no, was **not** able to renew a push certificate. I was able to generate a brand new MDM CSR 'vendor' certificate from the Apple Developer Portal, though.

**Comment by korylprince** [comment] 2021-02-09 20:09
@jessepeterson Thanks for getting the cert updated! Instead of the "signing certificate expired", I'm now also getting the signature error. At least that's one issue out of the way...

Interestingly, the signature link goes to http://www.apple.com/iphone/business/it/management.html for me.

**Comment by korylprince** [comment] 2021-02-10 15:06
I just got this response from Apple Support:

> So I have some good news and some bad news. From what the engineers are saying it seems that it has to do with the new Apple Worldwide Developer Relations Intermediate Certificate. MDMCert has updated their cert to the new guidelines which uses SHA-2 encryption instead of the older SHA-1. This has the trickle down effect of the creation of CSR’s also need to be updated. From what they could see the provided files are in SHA-1.

My understanding is new MDM vendor certs are SHA256 as opposed to SHA1, and they're signed with a [new intermediate,](https://developer.apple.com/support/expiration/) as @HernanPaez pointed to.

So basically two changes are necessary:

* The new intermediate needs to replace the old one in the chain in the request.
* The CSR signature needs to be created with SHA256, not SHA1

@jessepeterson will need to update mdmcert.download and `mdmctl` will need to be updated to reflect these changes.

I can create a PR for the `mdmctl` changes that @groob pointed to on Slack, but I don't have a MDM vendor cert so someone else would need to test.

**Comment by korylprince** [comment] 2021-02-10 15:42
I've submitted an (untested) PR with these changes - #725. Can someone with an MDM vendor cert build mdmctl from this PR and verify it generates a renewal request that works on identity.apple.com?

**Comment by korylprince** [comment] 2021-02-10 18:20
For anyone using mdmcert.download, @jessepeterson has updated it, and I was able to generate a new request and successfully renew my push cert!

There's been some confirmation on the MacAdmins slack that the PR I sent likely works, but I'm sure @groob will want more testing before including it.

As part of investigating, I wrote [a script](https://gist.github.com/korylprince/8cacf0ebde4ee145b942b319ac10a205) that will verify everything in your request (that you upload to identity.apple.com) looks right. It hope it proves useful in diagnosing issues you may have with your request.

**Closed** 2021-02-10 18:48 UTC

**Comment by jessepeterson** [comment] 2021-02-11 00:30
Further FYI for folks watching this issue: MicroMDM v1.8.0 was released with #725 merged in.

**Comment by jessepeterson** [comment] 2021-02-11 18:15
It would seem that the signature hash algorithm used is dependent on the issue date of the MDM vendor cert. We may want to conditionally switch between sha1 or sha2 hashes for signatures based on whatever that cutoff date is. For now folks can just use an older version if they have an older cert, I suppose.

**Comment by HernanPaez** [comment] 2021-02-11 19:03
Thanks! I've finally finished renewing my push certs and everything is working again!

I had another error where my Ubuntu instance couldn't connect to api.push.apple.com and therefore I couldn't send commands to the devices. The same error as @rodchristiansen reported

This are the commands I had to run on my ubuntu instance in order to trust the GeoTrust certificate.
I would like to keep this just for the record if anyone has the same problem

```
$ wget https://www.geotrust.com/resources/root_certificates/certificates/GeoTrust_Global_CA.pem
$ sudo cp GeoTrust_Global_CA.pem /usr/local/share/ca-certificates/GeoTrust_Global_CA.crt
$ sudo update-ca-certificates --fresh
```

**Comment by kozistan** [comment] 2025-04-18 19:10
Hi all, same thing is here again, after years as i can see. Any advice what to do? Im getting "Certificate Signature Verification failed because the [signing certificate](https://www.apple.com/iphone/business/it/management.html) is expired." and do not know how to decrypt with non expired apple CA, if I'm not wrong

**Comment by jessepeterson** [comment] 2025-04-18 20:47
> Hi all, same thing is here again, after years as i can see. Any advice what to do? Im getting "Certificate Signature Verification failed because the [signing certificate](https://www.apple.com/iphone/business/it/management.html) is expired." and do not know how to decrypt with non expired apple CA, if I'm not wrong

Have you tried renewing your MDM CSR certificate? That also needs to be renewed every year. The message you receive seems to indicate an expiry issue.

**Comment by Bob-FU** [comment] 2025-05-07 11:17
@jessepeterson hi. I also encounter the problem when I was trying to upload this signed CSR to identity.apple.com
(I'm using binaries from micromdm 1.13.0 release.)
```
# ./mdmctl mdmcert.download -new -email=john@doe.com
(I recieved an email with mdm_signed_request.20250507_xxxx.plist.b64.p7 attached in it)
# cat mdm_signed_request.20250507_xxxx.plist.b64.p7 | xxd -r -p > mdm_signed_request.20250507_xxxx.plist.p7
# openssl smime -decrypt -inform der -in mdm_signed_request.20250507_xxxx.plist.p7 -inkey mdmcert.download.pki.key > push_signed.req
```

I upload push_signed.req to apple and got the error message

<img width="621" alt="Image" src="https://github.com/user-attachments/assets/e7d49254-f341-4196-924c-caf751b3b6c7" />

**Comment by STSI-TerryB-blue** [comment] 2025-06-06 01:13
> [@jessepeterson](https://github.com/jessepeterson) hi. I also encounter the problem when I was trying to upload this signed CSR to identity.apple.com (I'm using binaries from micromdm 1.13.0 release.)
> 
> ```
> # ./mdmctl mdmcert.download -new -email=john@doe.com
> (I recieved an email with mdm_signed_request.20250507_xxxx.plist.b64.p7 attached in it)
> # cat mdm_signed_request.20250507_xxxx.plist.b64.p7 | xxd -r -p > mdm_signed_request.20250507_xxxx.plist.p7
> # openssl smime -decrypt -inform der -in mdm_signed_request.20250507_xxxx.plist.p7 -inkey mdmcert.download.pki.key > push_signed.req
> ```
> 
> I upload push_signed.req to apple and got the error message
> 
> <img alt="Image" width="621" src="https://private-user-images.githubusercontent.com/2800994/441210621-e7d49254-f341-4196-924c-caf751b3b6c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDkxNzI1MDksIm5iZiI6MTc0OTE3MjIwOSwicGF0aCI6Ii8yODAwOTk0LzQ0MTIxMDYyMS1lN2Q0OTI1NC1mMzQxLTQxOTYtOTI0Yy1jYWY3NTFiM2I2YzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDYwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA2MDZUMDExMDA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDYzY2I3OTk3Mjk2YjBlNDdkZmI0MjhkYjVkN2Q2Nzc5YzQ0NWRhYzdlMzM0ZWNhNTdjM2JjMjdmODZiZDE4NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.BT4FT5GmRCV1AZotomKcfyezTcylxO3hzNZ7NjGJiWM">

same issue here

**Comment by jessepeterson** [comment] 2025-06-06 01:19
Duplicates of #1069. Mdmcert.download is not an official MicroMDM project.
