### ISSUE TITLE
-http-debug  && profile install failed

### ISSUE THREAD

**Issue by zxyzhouxiaoyun** [micromdm/micromdm#908] opened 2023-07-29 08:23 UTC
I added -http-debug at startup because I wanted to know why my profile failed to install. I found that my mobile phone should have failed to check in, but there was no failure log in the log, because I did not get the check in event at all. It's not in the log either. What's wrong with this parameter

I'm using version 1.9, by the way

**Comment by korylprince** [comment] 2023-07-31 03:03
Closing as duplicate of #893.

**Closed by korylprince** 2023-07-31 03:03 UTC
