### ISSUE TITLE
Applying sha256 signed profile gives pkcs7 error

### ISSUE THREAD

**Issue by Beanow** [micromdm/micromdm#330] opened 2017-11-20 15:51 UTC
### What version of `micromdm` are you using?

`mdmctl version v1.2.0-3-g1f93a51-dirty`
i.e. the current master

### What `micromdm` command did you run?

`mdmctl apply profiles -f path/to/signed.mobileconfig`

### What did you expect to see?
mobileconfig is used as-is.

### What did you see instead?

```
pkcs7: cannot decrypt data: only RSA, DES, DES-EDE3, AES-256-CBC and AES-128-GCM supported
```

**Comment by Beanow** [comment] 2017-11-20 15:52
Note, the file is accepted by my apple device and shows it's a validated profile.

**Comment by groob** [comment] 2017-11-20 15:53
How was the profile signed?

**Comment by Beanow** [comment] 2017-11-20 15:55
```
openssl cms -sign \
	-signer capub.cert \
	-inkey capriv.key \
	-certfile appleint.cert \
	-nodetach \
	-outform der \
	-in unsigned.mobileconfig \
	-out signed.mobileconfig
```

**Comment by groob** [comment] 2017-11-20 16:02
If you just queue via the REST API an InstallProfile command, this should happen. But it will with mdmctl because it will try to read the encrypted profile here https://github.com/micromdm/micromdm/blob/e3348a9a301a250310f3dd663f5978cbd5592b09/profile/profile.go#L19-L31

**Comment by Beanow** [comment] 2017-11-20 16:18
Well I'm trying to set the enrolling profile `com.github.micromdm.micromdm.enroll` with this, so a command doesn't apply. Unless you mean the `/v1/profiles` internal API?

**Comment by groob** [comment] 2017-11-20 16:20
No. wouldn't work for the enrollment profile.

**Comment by jessepeterson** [comment] 2017-11-21 06:05
This should be supported. Is this a merely signed or actually encrypted profile? Pretty sure we've tested with signed profiles.

**Comment by jessepeterson** [comment] 2017-11-21 06:40
Just tried two signed profiles — one generated using Apple Configurator and another using `openssl`. Both worked as expected. My openssl invocation:

```
openssl smime \
	-sign \
	-signer signer.crt \
	-inkey signer.key \
	-outform DER \
	-nodetach \
	-in profile.mobileconfig \
	-out profile-signed.mobileconfig
```

**Comment by jessepeterson** [comment] 2017-11-21 06:43
Also for fun tested an enrollment profile, that works re-uploaded as a signed profile, too.

**Comment by jessepeterson** [comment] 2017-11-21 06:56
For even more fun I tested a signed, encrypted profile (since an encrypted profile is just a different plist XML structure) and that worked fine, too, even for an enrollment profile. :)   https://github.com/nmcspadden/ProfileSigner is nice here.

**Comment by Beanow** [comment] 2017-11-21 07:47
@jessepeterson can you try including an intermediate certificate with `-certfile` and see if that causes any trouble?

**Comment by Beanow** [comment] 2017-11-21 10:15
Digging around in https://github.com/fullsailor/pkcs7 the answer is fairly simple.
The profile was signed with sha256 and only sha1 is supported. For which the error message is incorrect as it's unrelated to decryption.

**Comment by Beanow** [comment] 2017-11-21 10:48
https://github.com/fullsailor/pkcs7/pull/19 seems like it would fix this.

**Comment by groob** [comment] 2017-11-21 14:14
So we are using my fork in micromdm/scep, but not in micromdm yet 

https://github.com/micromdm/scep/blob/cced6af4d385f2129bc9d6f0969293dba542f668/Gopkg.lock#L10-L15

https://github.com/micromdm/micromdm/blob/e3348a9a301a250310f3dd663f5978cbd5592b09/Gopkg.lock#L16-L20

I've made a bunch of improvements to the scep repo recently but haven't had the time to integrate them here. 
If we start using the latest version of the scep repo some of these problems would go away.

**Comment by jessepeterson** [comment] 2017-11-22 05:09
@Beanow thanks for tracking down the root cause and your work upstream!

**Comment by knightsc** [comment] 2018-06-16 18:39
I think with the recent merge of #440 this might be fixed now.

**Closed** 2018-06-22 21:39 UTC
Labels: bug

**Comment by jessepeterson** [comment] 2018-06-26 19:35
Has anyone actually tested signing using sha256? @Beanow would you mind testing with the newer version?
