### ISSUE TITLE
DEP Auto-Assigner not fully working

### ISSUE THREAD

**Issue by WardsParadox** [micromdm/micromdm#472] opened 2018-07-25 19:47 UTC
### What version of `micromdm` are you using?
micromdm version 1.3.1
### What `micromdm` command did you run?
`mdmctl apply dep-profiles -f dep_profile.json -filter='*'`
### What did you expect to see?
DEP profile assigning to all devices.
### What did you see instead?
DEP Profile is not assigning to new MacBook Pro (13/15-inch, 2018) models.

Manual assignment still works.

**Comment by jessepeterson** [comment] 2018-07-26 17:20
DEP auto-assigner will not "back"-assign previous/existing devices. It will only auto-assign _newly added_ devices in the DEP/ABM portal. This means newly purchased devices set for MDM server automatic assignment or if you _reassign_ a device from another MDM server to MicroMDM in the DEP/ABM portal.

**Comment by jessepeterson** [comment] 2018-07-26 17:32
Oh, interesting! That's very odd. The `success=1` means Apple told us the profile was successfully assigned. If you un-assign from the portal and re-assign to MicroMDM (and issue a sync) is it reproducible?

**Comment by WardsParadox** [comment] 2018-07-26 17:33
I tried that and it discovered it and stated the same message and same error. I tried it first thinking that I hadn't fully assigned it, but looking through the logs it did the same thing. I was only able to assign it manually before it pulled a profile.

**Comment by jessepeterson** [comment] 2018-07-27 19:12
@WardsParadox do other devices auto-assign okay? If it was assigning manually and not via the auto-assigner then it almost seems like there's a difference between the Apple DEP endpoint to Assign Devices vs. Defining a DEP Profile.

**Comment by WardsParadox** [comment] 2018-07-27 19:13
Sure seems like it. I haven't added any of the 2017 MBA's we just got and they are all getting the dep profile. That pro was so far the only issue.

**Comment by tomaswallentinus** [comment] 2018-09-09 13:40
I think it’s the same for new Macbook Air 13 as well. I will try if the pr works on monday :)

**Comment by jessepeterson** [comment] 2018-09-09 23:37
@tomaswallentinus There's been no changes to the auto-assigner logic. If it does not work for a specific model of computer, then it's virtually certain that this is an Apple-side problem.

**Comment by jessepeterson** [comment] 2020-01-06 21:27
@WardsParadox @tomaswallentinus have you seen this again, is it reproducible? We've been using the auto-assigner logic successfully for quite some time without issue.

**Comment by tomaswallentinus** [comment] 2020-01-06 21:34
Nop, haven't seen it since then. It could have been user error from my part back then.

**Comment by WardsParadox** [comment] 2020-01-07 21:16
Same, but no longer able to use micro :(

**Closed** 2020-01-08 16:17 UTC
