### ISSUE TITLE
how to enable activation lock?

### ISSUE THREAD

**Issue by dstmath** [micromdm/micromdm#996] opened 2024-05-08 12:50 UTC
### What version of `micromdm` are you using?
1.12.1
### What `micromdm` command did you run?
send a raw command
```
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Command</key>
    <dict>
        <key>RequestType</key>
        <string>Settings</string>
        <key>Settings</key>
        <array>
            <dict>
                <key>DeviceName</key>
                <string>NewName</string>
                <key>Item</key>
                <string>DeviceName</string>
            </dict>

           <dict>
                <key>Item</key>
                <string>MDMOptions</string>
                <key>MDMOptions</key>
                <dict>
                        <key>ActivationLockAllowedWhileSupervised</key>
                        <true/>
                </dict>
           </dict>
        </array>
    </dict>
    <key>CommandUUID</key>
    <string>0001_Settings</string>
</dict>
</plist>
```

### What did you expect to see?
when I leave the remote management, the activation lock is enabled
### What did you see instead?
when I leave the remote management, the activation lock is disabled.

My device is in abm.

And how to use activation lock?

The command is executed:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>ActivationLockBypassCode</key>
        <string>W83ML-D43DV-U6M1-A9GM-YCKA-L815</string>
        <key>CommandUUID</key>
        <string>d01c388b-8687-4794-a93d-9ac0c058d081</string>
        <key>Status</key>
        <string>Acknowledged</string>
        <key>UDID</key>
        <string>00008110-000579D01A82401E</string>
</dict>
</plist>
</plist>
```

**Comment by jessepeterson** [comment] 2024-05-08 22:33
```
        <key>Status</key>
        <string>Acknowledged</string>
```

Personally I don't have any experience with activation lock, so I can't say.

But: You're receiving a response from MicroMDM properly which means MicroMDM is working okay. How activation lock works with devices unfortunately is out of scope for MicroMDM — in other words "working as intended." This is an issue with how MDM works *on the device.* I'd suggest the #mdmdev channel on the [MacAdmins Slack](https://www.macadmins.org) or Apple Developer Forums or even filing Feedback with Apple.

Sorry we can't be of more help here!

**Closed** 2024-05-08 22:33 UTC

**Comment by jessepeterson** [comment] 2025-05-05 16:39
@abhimanyu95 that API endpoint is from the Apple DEP API of which MicroMDM has no direct support for. You might have better luck trying with [NanoDEP](https://github.com/micromdm/nanodep) which can use any arbitrary DEP API endpoint using the proxy.

**Comment by abhimanyu95** [comment] 2025-05-06 04:43
> Hi [@dstmath](https://github.com/dstmath), did you find a solution to this? Apple's https://developer.apple.com/documentation/devicemanagement/activation-lock-devices documentation seems to be incorrect, as the mentioned API returns 405 Method Not Allowed.

**Solution**
_For https://mdmenrollment.apple.com/device/activationlock API we have to also add X-Server-Protocol-Version:7 in the header and it will work and enable the Activation Lock for MDM._

@jessepeterson @dstmath

**Comment by jessepeterson** [comment] 2025-05-06 06:39
> **Solution** _For https://mdmenrollment.apple.com/device/activationlock API we have to add X-Server-Protocol-Version:7 in the header and it will work and enable the Activation Lock for MDM enrolled devices._

NanoDEP supports protocol version 7 by default, fwiw:

https://github.com/micromdm/nanodep/blob/5536f60bd3d97a787ead769de913f1a5d7561e8a/client/transport.go#L19
